name: platex

on:
  push:
    branches: ['master']

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
	with:
	  ref: gh-pages
      - name: build
      	run: |
	     sudo apt-get update; sudo apt-get install -y texlive texlive-lang-japanese; bash 0.sh



