name: platex

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup file
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - run: |
          sudo apt-get update; sudo apt-get install -y texlive texlive-lang-japanese; bash 0.sh; git config --local user.email "a175@users.noreply.github.com
"; git config --local user.name "a175" ; git commit -a -m'build pdf' ; git push




